eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
spring:
  application:
    name: school-service
  datasource:
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
application:
  config:
    students-url: http://localhost:9000/student