eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/student/**
        - id: school-service
          uri: http://localhost:8091
          predicates:
            - Path=/school/**
server:
  port: 8095